---
title: "GMIEC"
---
  
Welcome in **GMIEC**!! **GMIEC** is a framework, GMIEC, that integrates omics data (gene-expression, copy number variation, mutation, methylation) with data containing genomic coordinates of cis and/or trans epigenetic regulators (e.g. ChIP-seq). Then, at the level of the single patient, GMIEC identify groups of genes (modules) that share common genomic features. Then, using an external database, the genes in each module are associated with their own target drugs. Therefore, GMIEC allows the identification, at the level of the single patient, groups of genes that are regulated by the same epigenetic regulators (e.g. TFs), sharing common genomic features and associated with different number of drugs.

#### **Functionalities of GMIEC:**

- Identification of groups of genes with/without genomic alterations associated with drugs using **gene-expression**, **copy-number alteration**, **methylation**, **mutation**, **clinical data**.
- Analysis using only the annotated genes.
- Analysis using a custom list of genes.
- Analysis using all genes between the datasets.

#### **Functionalities of GMIEC-MD**
- Identification of groups of genes with/without genomic alterations associated with drugs using **predefined** number of datasets.
- Analysis using only the annotated genes.
- Analysis using a custom list of genes.
- Analysis using all genes between the datasets.

#### **Functionalities of VIS-GMIEC:**
- Exploration of the data at the level of groups of or single patient
- Summary of the scores, genes and drugs fo the modules for each single patient

#### **Functionalities of GMIEC-RESULTS:**
- Parse the output of GMIEC and select only the modules given different criterias.
- Visualize the results at the level of single patient.

#### **Manual of GMIEC:** 
The manual is available on the official github repository of GMIEC-shiny: https://github.com/guidmt/GMIEC-shiny

#### **Support:** 
-  https://github.com/guidmt/GMIEC-shiny
-  guidantonio.mt AT gmai.com

#### **Terms of use:** 
-  The features of GMIEC make it a tool that could be useful in the context of the data integration, data mining and data-exploration at the level of single patient. GMIEC is a tool that is provided only to perform analysis, exploratory analysis in basic and bioinformatic research with a scientific usage. GMIEC was not develop as tool to use in the clinical practice and authors decline each responsibility on its usage. See section terms of use for all details.




