---
title: "Manual of GMIEC"
---

#### **Dependencies**
GMIEC depends on several packages:

- bcp
- ChIPpeakAnno
- plyr
- stats
- shiny
- shinydashboard
- heatmaply
- klaR
- formattable
- kableExtra
- randomForest

### **How to install GMIEC**
Copy and paste the code inside the INSTALL.R on a R shell.

#### **How to run GMIEC in local:**

1. Go to https://github.com/guidmt/gmiec-shiny
2. Download the repository or use git-clone
3. Go in the folder with the application and:
   + From console **shinyAppDir(appDir="/mydir/GMIEC_shiny")**

### **A brief summary**
GMIEC consists of three application:
- GMIEC-MD for the integration of multi-omics data
- GMIEC-FD for the integration of only two data set
- GMIEC-VIS to visualize the results of GMIEC-MD and GMIEC-FD

#### **Step1: Methods of analysis**
GMIEC-MD implements two methods for the integration of the multi-omics data and the identification of groups of genes at the level of single patient.  **Method 1 (M1)**, The first method (M1) it is based on an unsupervised machine learning approach, here we implemented a random forest algorithm from random-Forest R-package. For each patient is generate a matrix used as input for random forest that integrate the data and compute the similarities measures between the points (proximity values).The vector with the values of proximity is used as input for k-means to identify cluster of genes. Each cluster will contain genes that shared common genomic features. **Method 2 (M2)**,GMIEC-MD and GMIEC-FD implements also a logic approach to iden-tify (method 2, M2), in each patient, the genes that has specifics genomic features. For each patient (i) a matrix Mi = (g x r), in which n are genes and r rules is generated (see supplementary data). If a gene respect a giv-en rule is marked as [1], otherwise [0].  The clustering of the matrix M is performed with k-mode using a number cluster defined by the user.

#### **Step2: Compute the scores**
In the case that GMIEC-MD was run to use M1, a S-score like is computed for each module to measure if a group of genes are oncogenic or suppressed. In parallel to this, we identified also if a module is druggable or not.  A module highly druggable is a module in which many genes are targeted by drugs. Finally we created a unique score to indicate the levels of alterations and druggability of a module. In the case that GMIEC is run with M2 or GMIEC-FD a level alteration module is compute (LAM score) to measure the level of genomic alteration. Similarly for M1, for each module an estimation   between the number of genes links with drugs (gtg) and the total number of genes in module (tgm) is computed. Also in this case a combine scores is computed.

#### **Annotation**
GMIEC-MD and GMIEC-FD can used as input genomic data such as ChIP-seq data (chromosome, start, end). In this case, the first step is the annotation of ChIP-seq data of a transcriptional factors are annotated using ChIPPeakAnno, considering a distance **(d)** of **(n)** bp. After this step the mean absolute deviation (MAD) of the annotated genes is estimated. Then, to filter the genes a bayesian analysis of change points of MAD is perfomed. This allowed to selected only the genes with high MAD values and without use a pre-determinate user threshold. In GMIEC this step is conducted by bcp function  implemented in bcp R-package. This function implements the Bayesian change point methods develop by Wang and Emerson (2015). Then, after that the selection of genes is perfomed, for each patient start the core of the GMIEC analysis. The main aim of the workflow is the identification of specifics genes that shares the same genomic alterations (e.g. copy number variation, methylation, gene-expression changes, mutation etc.). In our context we will use the term "module" to define groups of genes that share the same genomics alterations and that are regulated by the same transcriptional factors. The identification of modules involves the integration of all omics data available.

#### **Input of GMIEC-MD and GMIEC-FD:**

- **omics data**: gene-expression, copy-number epigenetics and mutations data in the form of tab-delimited files. In the case the genetic variants data, the user must create a file with only the mutations of interest (e.g. with deleterious variants). 
- **drugs-genes table**: a tab delimited file with the association between genes and drugs. The user can create a custom file selecting only the drugs and genes that are important for the disease of interest.
- **clinical data**: a tab delimited file with clinical variables to include in the analysis.
- **epigenetic data** (not mandatory): a bed file with chromosome, start, end. 
- **list of genes** (not mandatory): a list of genes of interest to consider for the analysis (e.g. genes of a pathway). The list of genes can be directly uploaded by the user. Otherwise if the user provides a file with genomic coordinates, the list of genes is obtained through a step of annotation. 

#### **Output of GMIEC-MD and GMIEC-FD:**
The output of GMIEC is a tab delimited file. This output contains the gene modules (GMs) and drug modules (DMs) identified during the analysis. The output reports also columns containing scores, that are a quantification of the levels of genomic alterations of the genes in GM, and the fraction of drugs links with a GMs. GMIEC allows also to gen-erate an html report (see figure S2) that can be interrogated directly click-ing on specific links. In particular, for each patient the groups of genes identified with common molecular features, the associated drugs and the clinical data provided by the user are reported. 

#### **How to run  GMIEC:**
If you use GMIEC-MD and GMIEC-FD two are the initial steps:

1. Upload all omics dataset 
2. Upload the data with the association drug-gene

1. **Analysis considering only the annotated genes**
   + Upload the bed file
   + Click on "Use only the annotated genes"
   + Select the number of clusters
   + Select if you want to run the analysis with "random + k-means (M1)"
   + Type the name for the output
   + Click on "Run Analysis"
   + When the analysis is finished click on "Download"
   
2. **Analysis considering only the annotated genes and TF**
   + Upload the bed file
   + Type the name of TF
   + Click on "Use only the annotated genes and explore the TF"
   + Select the number of clusters
   + The options "random + k-means (M1)" is not available in this case
   + Type the name for the output
   + Click on "Run Analysis"
   + When the analysis is finished click on "Download"
   
3. **Analysis considering using a gene-list**
   + Click on "Use a gene-list" (provide a tab-delimited file with one column reporting the genes)
   + Upload the gene-list
      + Click on "Use only the annotated genes and explore the TF"
   + Select the number of clusters
   + Select if you want to run the analysis with "random + k-means (M1)"
   + Click on "Run Analysis"
   + When the analysis is finished click on "Download"   
  
4. **Analysis considering using all genes**
   + Click on "Use all genes"
   + The options "random + k-means (M1)" is not available in this case
   + Click on "Run Analysis"
   + When the analysis is finished click on "Download"
   
- **Parameters for GMIEC**
   + Click on "Use all genes"
   + Click on "Run Analysis"
   + When the analysis is finished click on "Download" 
   
#### **How to run  GMIEC-FD**
   + On the menu of GMIEC-Shiny, click on GMIC-FD and use the same procedures described for GMIEC-MD to analyze the data.
