---
  title: "Terms of use"
---
GMIEC Shiny App for the integrations of omics data, drugs databese and identifcation of groups of genes alterated or not.
Copyright (C) 2018  Guidantonio Malagoli Tagliazucchi

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

The features of GMIEC make it a tool that could be useful in the context of the data integration, data mining and data-exploration at the level of single patient. GMIEC is a tool that is provided only to perform analysis, exploratory analysis in basic and bioinformatic research with a scientific usage. GMIEC was not develop as tool to use in the clinical practice and authors decline each responsibility on its usage.

You may contact the author of this code, Guidantonio MT, at <guidantonio.mt AT gmail.com>